### ISSUE TITLE
Exchange versions

### ISSUE THREAD

**Issue by lean0x2F** [dirkjanm/PrivExchange#2]
Hi dude :) nice work! 

I was thinking if you could add an option to select the target Exchange version. 

`<t:RequestServerVersion Version="Exchange2013" />`

This would not work when attacking Exchange 2010 for example. The possible strings are:

```
Exchange2010_SP1
Exchange2010_SP2
Exchange2010_SP3
Exchange2013
Exchange2016
```

Thank you!!

**Comment by dirkjanm** [comment]
Should be fixed! Thanks for the report :)
