### ISSUE TITLE
Exchange 2010

### ISSUE THREAD

**Issue by learncs-max** [dirkjanm/PrivExchange#22]
line 215: if int(versioninfo.get('MajorVersion')) == 14:
  logging.info('Exchange 2010 detected. This version is not vulnerable to PrivExchange.')

line 67: EXCHANGE_VERSIONS = ["2010_SP1","2010_SP2","2013","2016"]

I'm so confused that if all service pack of Exchange 2010 are not affected by privexchange or just SP3.

**Comment by dirkjanm** [comment]
To my knowledge none of the 2010 versions are vulnerable. The list of EXCHANGE_VERSIONS are a actually possible API Dialects (not vulnerable exchange versions). For example Exchange 2016 can still use the 2010_SP1 dialect for API calls.
