### ISSUE TITLE
getaddrinfo fails with Name or service not known

### ISSUE THREAD

**Issue by mgeeky** [dirkjanm/PrivExchange#4]
Hi,
I'm strugling to get privexchange issue a request to my EWS, but all it does it merely fails to resolve my target. For a testing purposes, I'm in the same segment as target machine (Exchange 2013), my linux host is able to resolve that exch01 DNS name, also nmap points me that it's 443 is open. Any hints left to share?

![screenshot 012](https://user-images.githubusercontent.com/654344/51779478-d8f60400-2107-11e9-890b-c0e9efae97e4.png)

**Comment by dirkjanm** [comment]
You seem to have entered the full URL of the Exchange EWS, where only the hostname is required for privexchange.py

**Comment by mgeeky** [comment]
Well, you were right about this one. My mistake. Any hint why the `requests` part might be failing this time?

![screenshot 013](https://user-images.githubusercontent.com/654344/51808713-de825400-2297-11e9-9085-8ab830f4cdd2.png)

**Comment by mgeeky** [comment]
Well, you were right about this one. My mistake. Any hint why `session.request` might be failing this time?
Target server has no firewall rules in place, TCP 80 and 443 is perfectly reachable as tested with nmap, the EWS there is up & running fine. Also, there are no issues with proxychains, other firewall/network related.
My `devatt.` was added to `/etc/hosts` so no issue with DNS resolving either.

![screenshot 013](https://user-images.githubusercontent.com/654344/51808749-39b44680-2298-11e9-9d70-4dfab876afdc.png)

**Comment by dirkjanm** [comment]
Proxychains is reporting a timeout, so something is going wrong somewhere on the network, unrelated to privexchange.py
