### ISSUE TITLE
Error on: " Enumerating relayed user's privileges."

### ISSUE THREAD

**Issue by h4ckd0tm3** [dirkjanm/PrivExchange#7]
[*] HTTPD: Received connection from X.X.X.X, attacking target ldap://DC.LOCAL
[*] HTTPD: Client requested path: /privexchange/
[*] HTTPD: Received connection from X.X.X.X, attacking target ldap://DC.LOCAL
[*] HTTPD: Client requested path: /privexchange/
[*] HTTPD: Client requested path: /privexchange/
[*] Authenticating against ldap://DC.LOCAL as DOMAIN\XCHSRV$ SUCCEED
[*] Enumerating relayed user's privileges. This may take a while on large domains

[*] Enumerating relayed user's privileges. This may take a while on large domains
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 313, in run
    userSid, privs = self.validatePrivileges(self.username, domainDumper)
  File "build/bdist.linux-x86_64/egg/impacket/examples/ntlmrelayx/attacks/ldapattack.py", line 165, in validatePrivileges
    user = self.client.entries[0]
IndexError: list index out of range

Any ideas?

**Comment by h4ckd0tm3** [comment]
Solved it. This happens if the ldap DC is not in the same subdomain.

Example: DC.ad.local and the user is in sub.ad.local you have to go with the domain controller in the same sub domain -> DC.sub.ad.local

**Comment by dirkjanm** [comment]
Thanks for the feedback, this indeed occurs if the username of the relayed account is not found in LDAP.

**Comment by KaisserbenDll** [comment]
I am running into the  same error. Care to explain how did you fix it ? I believe I am on the same Subnet as the DC.
