### ISSUE TITLE
Tested on Exchange 2016 (CU11) on Server 2016, relayed to a Server 2016 DC

### ISSUE THREAD

**Issue by h4ckd0tm3** [dirkjanm/PrivExchange#8]
Well not an issue actually ^^
Just wanted to let you know that it seems, that you cannot get to Domain Admin in an environment where the exchange is 2016 CU11 on Server 2016 and the DC is Server 2016. I mean it sort of works, the API Call succeeds and so does the Authentication of the Exchange Account.

I got the Domain Information (Users, Policies...) but after enumerating user rights nothing was printed, so i assume that nothing was found?

Hope this helps :)

**Comment by dirkjanm** [comment]
Then I assume Exchange doesn't have the required privileges in the domain. Could be that Exchange is installed in Active Directory split permissions mode.

**Comment by h4ckd0tm3** [comment]
I see, will check and come back with feedback!

**Comment by h4ckd0tm3** [comment]
Ok, Exchange has RBAC split permissions activatet. Seems that RBAC works similar to the AD split permission mode.

**Comment by dirkjanm** [comment]
Thanks for the feedback, closing!
